### POST an login
POST {{url}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "username":"Jasmin",
  "password": "1234"
}

### POST an user
POST {{url}}/auth/user/addrole
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIkZhdGltYVwiIiwic3ViIjoiSmFzbWluIiwiZXhwIjoxNzMzMjQyODgxLCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Ikphc21pbiJ9.CIhOnmzMM_S-cWBB1JnyprQYdF2syKfrxirXxmZjddc


{
  "role": "user"
}

### POST an register
POST {{url}}/auth/register
Content-Type: application/json
Accept: application/json

{
  "username":"Jasmin",
  "password": "1234"
}


