### POST request to add songs to a playlist
POST {{url}}/playlists/19/songs
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJGYXRpbWEiLCJzdWIiOiJKb24iLCJleHAiOjE3MzUxODIwNTgsInJvbGVzIjoidXNlciIsInVzZXJuYW1lIjoiSm9uIn0.gzo8zMG6W19ZWEUXnb4XxshCZgNUsFQ8mK5bU9aG6Ls

[
  { "title": "Song 1", "artist": "Artist 1", "genre": "Pop" },
  { "title": "Song 2", "artist": "Artist 2", "genre": "Jazz" }
]

### GET request to fetch all songs in a playlist
GET {{url}}/playlists/20/songs
Accept: application/json

### GET request to fetch a specific song by ID "good"
GET {{url}}/songs/40
Accept: application/json

### PUT request to update a song by ID
PUT {{url}}/songs/5
Content-Type: application/json
Accept: application/json

{
  "title": "Updated Song Title",
  "artist": "Updated Artist",
  "genre": "Updated Genre"
}

### DELETE request to delete a song by ID
DELETE {{url}}/songs/40
Accept: application/json
