### GET request to check compatibility between two users "good"
GET {{url}}/users/Meena/compatibility/Jon
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJGYXRpbWEiLCJzdWIiOiJNZWVuYSIsImV4cCI6MTczNTI0NDc1NCwicm9sZXMiOiJ1c2VyIiwidXNlcm5hbWUiOiJNZWVuYSJ9.wUuEPklL18y-kvxQDFQYtksFq9UJDD_u8ueoFYbktmk

